spring:
  application:
    name: orderMng

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_workflow_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

app:
  jwt:
    secret: YJBp7ygMXFrAoeFJEOb5v3B3P6uUKcgB5kQicLGBhIQi0PzLQveOJYQglQpP2d6S
    expiration: 3600000
    refresh:
      expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.jeevan.orderMng: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

